# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version=0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "devices-sam-cli"

[default.build.parameters]
cached = true
parallel = true
use_container = true
beta_features = false
build_image = ["hiperium/native-image-builder:latest"]

[default.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
beta_features = false
disable_rollback = true

[default.sync.parameters]
watch = false
