AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM Template for Devices module.'

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: "provided.al2023"
    Architectures:
      - "arm64"

Parameters:
  SpringProfile:
    Type: String
    Default: "dev"
    Description: "Spring profile for the functions."

Resources:
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Devices"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "cityId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "cityId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"

  DevicesDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./city-devices-data-function
      FunctionName: "city-devices-data-function"
      Description: "Device Data function used only for internal services."
      Handler: "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DevicesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: "makefile"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DevicesDataFunction}"
      RetentionInDays: 7

Outputs:
  DeviceDataFunctionArn:
    Description: "Device Data function ARN."
    Value: !GetAtt DevicesDataFunction.Arn

  DevicesTableArn:
    Description: "Devices DynamoDB table ARN."
    Value: !GetAtt DevicesTable.Arn

  DeviceDataFunctionIamRoleArn:
    Description: "Implicit IAM Role ARN created for the Device Data function."
    Value: !GetAtt DevicesDataFunctionRole.Arn
