AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM Template for Devices module.'

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: "provided.al2023"
    Architectures:
      - "arm64"

Parameters:
  SpringProfile:
    Type: String
    Default: "dev"
    Description: "Spring profile for the functions."

Resources:
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Devices"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "cityId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "cityId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"

  DeviceUpdateFunctionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "device-update-function-dlq"

  DeviceDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./device-data-function
      FunctionName: "device-data-function"
      Description: "Device Data function used for internal services only."
      Handler: "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DevicesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: "makefile"

  DeviceUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./device-update-function
      FunctionName: "device-update-function"
      Description: "Device Update function used for internal services only."
      Handler: "org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest"
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeviceUpdateFunctionDLQ.Arn
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: "cities-event-bus"
            Pattern:
              source:
                - "hiperium.city.tasks.api"
              detail-type:
                - "ExecutedTaskEvent"
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DevicesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: "makefile"

  DeviceDataLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DeviceDataFunction}"
      RetentionInDays: 7

  DeviceUpdateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${DeviceUpdateFunction}"
      RetentionInDays: 7

Outputs:
  DevicesTableArn:
    Description: "Devices DynamoDB table ARN."
    Value: !GetAtt DevicesTable.Arn

  DeviceDataFunctionArn:
    Description: "Device Data function ARN."
    Value: !GetAtt DeviceDataFunction.Arn

  DeviceUpdateFunctionArn:
    Description: "Device Updates function ARN."
    Value: !GetAtt DeviceUpdateFunction.Arn

  DeviceDataFunctionIamRoleArn:
    Description: "IAM Role ARN for the Device Data function."
    Value: !GetAtt DeviceDataFunctionRole.Arn

  DeviceUpdateFunctionIamRoleArn:
    Description: "IAM Role ARN created for the Device Updates function."
    Value: !GetAtt DeviceUpdateFunctionRole.Arn
