AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for Devices module.'

Globals:
  Function:
    Timeout: 30     # seconds
    MemorySize: 512 # MB
    Runtime: provided.al2023
    Architectures:
      - arm64

Parameters:
  ResourceDeletionPolicy:
    Type: String
    Default: 'Delete'
    AllowedValues:
      - Retain
      - Delete
    Description: 'Deletion policy for table/log resources. For Snapshot, you need to create a manual backup before deleting the stack to preserve the data.'

  EventBusName:
    Type: String
    Default: 'cities-event-bus'
    Description: 'Event bus name for the Hiperium City project.'

  SpringProfile:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - qa
      - prod
    Description: 'Spring profile for the functions.'

  LogRetentionInDays:
    Type: Number
    Default: 7
    AllowedValues:
      - 7
      - 14
      - 30
    Description: 'Log retention in days for the functions.'

Resources:
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'Devices'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: S
        - AttributeName: 'cityId'
          AttributeType: S
      KeySchema:
        - AttributeName: 'id'
          KeyType: HASH
        - AttributeName: 'cityId'
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: !Ref ResourceDeletionPolicy

  ReadFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}/DeviceReadFunction"
      RetentionInDays: !Ref LogRetentionInDays
    UpdateReplacePolicy: Retain
    DeletionPolicy: !Ref ResourceDeletionPolicy

  ReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./device-read-function
      FunctionName: 'device-read-function'
      Description: 'Read device data function.'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      LoggingConfig:
        LogGroup: !Ref ReadFunctionLogGroup
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DevicesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: makefile

  UpdateFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}/DeviceUpdateFunction"
      RetentionInDays: !Ref LogRetentionInDays
    UpdateReplacePolicy: Retain
    DeletionPolicy: !Ref ResourceDeletionPolicy

  UpdateFunctionDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 'device-update-function-dlq'
      VisibilityTimeout: 300            # 5 minutes
      MaximumMessageSize: 262144        # 256 KB
      MessageRetentionPeriod: 1209600   # 14 days
      ReceiveMessageWaitTimeSeconds: 20
    UpdateReplacePolicy: Retain
    DeletionPolicy: !Ref ResourceDeletionPolicy

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./device-update-function
      FunctionName: 'device-update-function'
      Description: 'Update device data function.'
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      LoggingConfig:
        LogGroup: !Ref UpdateFunctionLogGroup
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt UpdateFunctionDLQ.Arn
      Events:
        EventBridgeEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: !Ref EventBusName
            Pattern:
              source:
                - 'hiperium.city.tasks.api'
              detail-type:
                - 'ExecutedTaskEvent'
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DevicesTable
        - DynamoDBWritePolicy:
            TableName: !Ref DevicesTable
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref SpringProfile
    Metadata:
      BuildMethod: makefile

  UpdateEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'device-update-event-rule'
      Description: 'Update Device Event Rule'
      EventBusName: !Ref EventBusName
      State: ENABLED
      EventPattern:
        source:
          - 'hiperium.city.tasks.api'
        detail-type:
          - 'ExecutedTaskEvent'
      Targets:
        - Arn: !GetAtt UpdateFunction.Arn
          Id: 'DeviceUpdateFunctionTarget'
          RetryPolicy:
            MaximumRetryAttempts: 3
            MaximumEventAgeInSeconds: 300
          DeadLetterConfig:
            Arn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${EventBusName}-dlq"

  UpdateEventToLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UpdateFunction
      Action: lambda:InvokeFunction
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt UpdateEventRule.Arn

  UpdateEventToSqsPermission:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${EventBusName}-dlq"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'events.amazonaws.com'
            Action: 'sqs:SendMessage'
            Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${EventBusName}-dlq"
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt UpdateEventRule.Arn

Outputs:
  DevicesTableArn:
    Description: 'Devices DynamoDB Table ARN.'
    Value: !GetAtt DevicesTable.Arn

  ReadFunctionArn:
    Description: 'Read Device Function ARN.'
    Value: !GetAtt ReadFunction.Arn

  UpdateFunctionArn:
    Description: 'Update Device Function ARN.'
    Value: !GetAtt UpdateFunction.Arn

  UpdateEventRuleArn:
    Description: 'Update Device Event Rule ARN.'
    Value: !GetAtt UpdateEventRule.Arn
